//! Migration: create the `upload_sessions` table.
//!
//! Supports the resumable HTTP upload pipeline (Stage 7.5).  Each row tracks
//! one in-progress multi-chunk upload from a web client.

use sea_orm_migration::prelude::*;

use super::m20260220_000001_create_users::Users;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(UploadSessions::Table)
                    .if_not_exists()
                    // UUIDv4 string — generated by the server on PREPARE.
                    .col(
                        ColumnDef::new(UploadSessions::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    // Foreign key → users.id; cascades on user deletion.
                    .col(ColumnDef::new(UploadSessions::UserId).string().not_null())
                    // VFS parent directory that will hold the final file.
                    .col(ColumnDef::new(UploadSessions::ParentId).string().not_null())
                    // Filename to store in the VFS when the upload completes.
                    .col(ColumnDef::new(UploadSessions::FileName).string().not_null())
                    // Total file size (bytes).  Stored as big_integer (i64) for
                    // cross-backend compatibility; effectively supports up to ~9.2 EiB.
                    .col(
                        ColumnDef::new(UploadSessions::TotalSize)
                            .big_integer()
                            .not_null(),
                    )
                    // SHA-256 hex digest of the complete file.  Used for fast-path
                    // deduplication at PREPARE time and integrity check at COMPLETE.
                    .col(
                        ColumnDef::new(UploadSessions::ContentHash)
                            .string()
                            .not_null(),
                    )
                    // Optional MIME type hint from the client.
                    .col(ColumnDef::new(UploadSessions::MimeType).string().null())
                    // Fixed HTTP-chunk size negotiated at PREPARE time.
                    .col(
                        ColumnDef::new(UploadSessions::ChunkSize)
                            .big_integer()
                            .not_null(),
                    )
                    // Total number of HTTP chunks expected (ceil(total_size / chunk_size)).
                    .col(
                        ColumnDef::new(UploadSessions::ChunkCount)
                            .integer()
                            .not_null(),
                    )
                    // JSON array of received chunk indices, e.g. `[0,1,3]`.
                    // Updated atomically in a transaction whenever a chunk arrives.
                    .col(
                        ColumnDef::new(UploadSessions::ReceivedChunks)
                            .text()
                            .not_null()
                            .default("[]"),
                    )
                    // "pending" | "complete" | "cancelled"
                    .col(
                        ColumnDef::new(UploadSessions::Status)
                            .string()
                            .not_null()
                            .default("pending"),
                    )
                    .col(
                        ColumnDef::new(UploadSessions::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    // Hard deadline — the server will purge the session and its
                    // temp chunks once this timestamp is reached.
                    .col(
                        ColumnDef::new(UploadSessions::ExpiresAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_upload_sessions_user_id")
                            .from(UploadSessions::Table, UploadSessions::UserId)
                            .to(Users::Table, Users::Id)
                            .on_delete(ForeignKeyAction::Cascade)
                            .on_update(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        // Index on user_id — list sessions for a given user.
        manager
            .create_index(
                Index::create()
                    .name("idx_upload_sessions_user_id")
                    .table(UploadSessions::Table)
                    .col(UploadSessions::UserId)
                    .to_owned(),
            )
            .await?;

        // Index on expires_at — efficient GC sweep.
        manager
            .create_index(
                Index::create()
                    .name("idx_upload_sessions_expires_at")
                    .table(UploadSessions::Table)
                    .col(UploadSessions::ExpiresAt)
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(UploadSessions::Table).to_owned())
            .await
    }
}

// ─── Iden enum ────────────────────────────────────────────────────────────────

#[derive(Iden)]
pub enum UploadSessions {
    Table,
    Id,
    UserId,
    ParentId,
    FileName,
    TotalSize,
    ContentHash,
    MimeType,
    ChunkSize,
    ChunkCount,
    ReceivedChunks,
    Status,
    CreatedAt,
    ExpiresAt,
}
