[package]
name    = "jiezi-cloud-core"
version = "0.1.0"
edition = "2024"
description = "Core types, trait interfaces, domain models and events for Jiezi Cloud"

[dependencies]
async-trait.workspace = true
bytes.workspace       = true
chrono.workspace      = true
serde.workspace       = true
serde_json.workspace  = true
thiserror.workspace   = true
tracing.workspace     = true
uuid.workspace        = true

[dev-dependencies]
tokio = { workspace = true }
